frazoj = ["Ne skribu \"Kiel vi fartas?\". Babilu pri ",
          "Ĉu vi estas kielvifartasulo? Pli bone estas rakonti pri vi. Ekzemple, interesa temo estas ",
          "_\"La plej grava formulo por sukceso estas scii kiel paroli kun homoj.\"\nTheodore Roosevelt_\n\n DO ĈESU SKRIBI 'KIEL VI FARTAS?'. PAROLU PRI ",
          "Interesaj temoj gravas. Parolu pri ",
          "Bone 🦴. Mi volas paroli pri ",
          "Se mi tajpus \"Bone\", kion vi skribus poste?",
          "Bip-bup🤖. Parolu pri ",
          "_\"La sola lukso, kiun mi scias, estas la lukso de homa komunikado.\"_\nAntoine de Saint-Exupery\n\nĈi tio estas malbona demando por komenci babiladon. Mi ege pli ŝatus se vi parolus pri ",
          "Kiam mi lernis Esperanton, mi pensis ke mi parolos pri ",
          "Malbone. Mi ne povas trovi esperantan videon pri ",
          "Se vi ne scias, pri kio babili, parolu pri ",
          "Mi havas ideon, pri kio ni povus paroli. Pri "]
ideoj = ["hundoj. Mi persone ne ŝatas ilin", "katoj. Mi ŝatas ke ili estas memstaraj, sed mi ne volas havi ilin kiel hejmbestojn ", "viaj revoj. Mi esperas, ke ni atingos Finan Venkon", "mi. Mi bonegas, ĉu ne?", "komerco kaj Esperanto. Kial ankoraŭ ne ekzistas multe da e-aj entreprenistoj?", "kantoj. Mia plej ŝatata estas La fina venk'", "esperantaj memeoj. Mi faris unu: https://i.redd.it/sc17rr5b8or51.jpg", "programado. Ĉu vi sciis, ke mi estis programita kun mia oĉjo Python?", "WebArchive. (Nu, https://web.archive.org/). Mi trovis tie malnovan version de lernu.net", "animeoj. Mi nur komencis spekti Tokian Ĥulon",
         "hmm... vetero. Estas 22°C ĉe mi, ĉar mi sidas (kiel ĉiam) hejme", "mangaĵoj. Kio estas pli bongusta: suŝioj aŭ pico?", "tradicia kuirarto. Ĉu robotoj havas tradiciajn manĝaĵojn? Hmm", "filmoj. Mi planas spekti \"Mi, roboto\"-n, ĉar tie oni parolas pri miaj gefratoj.", "hobioj. Mi ŝatas kostumludi. Jen: https://clck.ru/TB2HZ", "paradoksoj. Ekzemple, kial preni libron el biblioteko estas bone, sed elŝuti ĝin el pirata retejo estas malbone?", "sporto. Miaj fratoj ŝatas ludi je futbalo. Jen fotaĵo: https://clck.ru/TB2UE", "famuloj. Ĉu esti famulo estas bone aŭ ne? Mi volus esti malkonatega, tiel ŝarĝo je servilo estus pli malalta", "lingvoj. Banala demando: kiun lingvon vi volus paroli senerare? Mi volas esti sperta je programlingvo.", "vojaĝado. Kien vi iru: ĉe maro aŭ sur montoj? Mi preferus estis sur montoj, ĉar mi ne estas akvorezista",
         "", "", "", "", "", "", "", "", "", "",
         "", "", "", "", "", "", "", "", "", "",
         "", "", "", "", "", "", "", "", "", "",
         "", "", "", "", "", "", "", "", "", "",
         "", "", "", "", "", "", "", "", "", "", 
         "", "", "", "", "", "", "", "", "", "", 
         "", "", "", "", "", "", "", "", "", "", 
         "", "", "", "", "", "", "", "", "", "", ]
